### ISSUE TITLE
Selected item wrong width on initial load

### ISSUE THREAD

**Issue by barenddev** [KazaiMazai/SwiftySegmentedPicker#5]
When the view is initially loaded, the width calculation for the text is incorrect, which causes the underline to be squished.  In my case, initial width printed out at around 30 pixels, but after you switch index and back it does get the correct width of around 100.  Any ideas on how to resolve this?

```
let titles = ["Full Balance", "Other Amount"]

SegmentedPicker(
                    titles,
                    selectedIndex: Binding(
                        get: { selectedIndex },
                        set: { selectedIndex = $0 }),
                    selectionAlignment: .bottom,
                    content: { item, isSelected in
                        Text(item)
                            .foregroundColor(isSelected ? .black : .gray )
                            .padding(.horizontal, 16)
                            .padding(.vertical, 8)
                    },
                    selection: {
                        VStack(spacing: 0) {
                            Spacer()
                            Color.black.frame(height: 1)
                        }
                    })
                    ```

**Comment by KazaiMazai** [comment]
@barenddev I've made an improvement should fix the issue that you faced. 
Lemme know if it worked for you.

**Comment by barenddev** [comment]
@KazaiMazai I tested your changes and can confirm it resolves the sizing problem on initialization for me.  Thanks for looking into this!

**Comment by KazaiMazai** [comment]
> @KazaiMazai I tested your changes and can confirm it resolves the sizing problem on initialization for me. Thanks for looking into this!

Awesome, thank you!
